apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: 558655763449.dkr.ecr.us-east-1.amazonaws.com/clo835-a2@sha256:655405919c0e70ebd3f7f266544eba9c98afb7ddd6af37d684b8b74299f1244d
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306