apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: employees
  