---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-v2
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web-app
        image: 877646386798.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:appv2
        env:
          - name: DBHOST
            value: "mysql-svc.sqldb.svc.cluster.local"
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DBPWD
            value: "pw"
        ports:
          - containerPort: 8080
        imagePullPolicy: Always