apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: sqldb
spec:
  containers:
  - name: mysql
    image: 877646386798.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:db
    env:
      - name: MYSQL_ROOT_USER
        value: "root"
      - name: MYSQL_ROOT_PASSWORD
        value: "pw"
    ports:
      - containerPort: 3306
    imagePullPolicy: Always
