apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: sqldb
  labels:
    app: mysql
spec:
  selector:
    name: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
