---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
  labels:
    course: clo835
    week: as2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: 877646386798.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:db
   