name: Deploy to ECR

on: 
  push:
    branches: [ dev ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: |
        
        # MYSQL Docker build and push
        docker build -f Dockerfile_mysql -t $ECR_REGISTRY/clo835-assignment2:dbv2 .
        docker push $ECR_REGISTRY/clo835-assignment2:dbv2
        
        # APP Docker build and push
        docker build -f Dockerfile -t $ECR_REGISTRY/clo835-assignment2:appv2 .
        docker push $ECR_REGISTRY/clo835-assignment2:appv2
        
